# Tyler Gohr Portfolio - Local Development Docker Compose
# For testing containerized deployment locally

version: '3.8'

services:
  portfolio:
    build:
      context: .
      dockerfile: Dockerfile
      target: runner
    container_name: tylergohr-portfolio
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - HOSTNAME=0.0.0.0
      - PORT=3000
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--no-verbose", "--tries=1", "--spider", "http://localhost:3000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - portfolio-network

  # Optional: Add nginx reverse proxy for production-like testing
  nginx:
    image: nginx:alpine
    container_name: tylergohr-nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    depends_on:
      - portfolio
    restart: unless-stopped
    networks:
      - portfolio-network
    profiles:
      - production-test

networks:
  portfolio-network:
    driver: bridge

# Volumes for persistent data (if needed in future)
volumes:
  portfolio-data:
    driver: local